0.1.2
New version logic in github action and hopefully better dependency
versions

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -16,36 +16,32 @@ jobs:
       - name: Set up Node.js
         uses: actions/setup-node@v3
         with:
-          node-version: '16' # or the version of Node.js you use
+          node-version: '20'
           registry-url: 'https://registry.npmjs.org'
+
+      - name: Extract version from commit message
+        id: extract_version
+        run: |
+          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
+          echo "Commit Message: $COMMIT_MESSAGE"
+          VERSION=$(echo "$COMMIT_MESSAGE" | head -n 1 | grep -Eo '^[0-9]+\.[0-9]+\.[0-9]+')
+          if [ -z "$VERSION" ]; then
+            echo "Error: No version number found in the commit message."
+            exit 1
+          fi
+          echo "::set-output name=version::$VERSION"
+
+      - name: Verify version matches package.json
+        id: verify_version
+        run: |
+          PACKAGE_VERSION=$(jq -r '.version' package.json)
+          if [ "$PACKAGE_VERSION" != "${{ steps.extract_version.outputs.version }}" ]; then
+            echo "Error: Version number in commit message does not match package.json"
+            exit 1
+          fi
 
       - name: Install dependencies
         run: npm install
-
-      - name: Fetch previous commit
-        run: git fetch --depth=2
-
-      - name: Get previous commit package.json
-        run: |
-          if git cat-file -e HEAD~1:package.json; then
-            git show HEAD~1:package.json > package_previous.json
-          else
-            echo '{}' > package_previous.json
-          fi
-
-      - name: Compare versions
-        id: version_check
-        run: |
-          CURRENT_VERSION=$(jq -r '.version' package.json)
-          PREVIOUS_VERSION=$(jq -r '.version' package_previous.json)
-          echo "Current version: $CURRENT_VERSION"
-          echo "Previous version: $PREVIOUS_VERSION"
-          if [ "$CURRENT_VERSION" == "$PREVIOUS_VERSION" ]; then
-            echo "Version has not changed."
-            exit 1
-          else
-            echo "Version has changed."
-          fi
 
       - name: Build the project
         run: npm run build
